---
version: '2'

services:

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=setecastronomy
    volumes:
      - postgres_data:/var/lib/postgresql/data

  felicitas:
    build: .
    image: felicitas
    environment:
      - PGDB=felicitas_development
      - PGHOST=postgres_db
      - PGPASSWORD=setecastronomy
      - PGPORT=5432
      - PGROLES=felicitas
      - PGUSER=postgres
      - RACK_ENV=development
      - RAILS_ENV=development
      - TMP=/tmp/felicitas
    depends_on:
      - postgres_db
    ports:
      - "3000:3000"
    volumes:
      - felicitas_sync:/srv/felicitas/:nocopy

volumes:

  postgres_data:

  felicitas_sync:
    external: true
