#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PSQL_CMD="psql -e -h $PGHOST -p $PGPORT -U $PGUSER"
IFS=', ' read -r -a ROLES <<< "$PGROLES"

echo "Attempting to create roles..."
for role in "${ROLES[@]}"
do
  $PSQL_CMD -c "CREATE ROLE $role WITH LOGIN"
done
echo "...done."

$PSQL_CMD -c "CREATE DATABASE $PGDB"
