#!/bin/bash -e
export SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# https://rvm.io/workflow/scripting
# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
fi

rvm use $(cat $SRC/.ruby-version)@$(cat $SRC/.ruby-gemset)
docker-sync start -c $SRC/docker-sync.yml
docker-compose -f $SRC/docker-compose.yml -f $SRC/docker-compose-dev.yml up --build -d
