---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <% ENV.fetch("PGUSER") { "postgres" } %>
  password: <% ENV.fetch("PGPASSWORD") { "" } %>
  timeout: 5000

development:
  <<: *default
  database: felicitas_development

test:
  <<: *default
  database: felicitas_test

production:
  <<: *default
  database: felicitas_production
